# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Introdução ao pandas
#SÉRIES
import pandas as pd

# Criando uma série sem especificar os indices
Obj = pd.Series([67,78,-56,13])

Obj

type(Obj)

Obj.values # Mostra os valores da série

Obj.index# Mostra o RangeIndex dos indices da série. start=0, stop=4, step=1)

#Criando uma série e especificando os indices
Obj2 = pd.Series([67,12,35,45], index= ['a','b','c','d'])

Obj2

Obj2.values

Obj2.index

Obj2[Obj2 > 3] # Mostra o valores maiores que 3 contidos na série

Obj2['b'] # Busca o valor de um indice especifico

'd' in Obj2 # Verifica se há o na serie , retorna True ou False

# Criando uma série de dados passando um dicionario como parametro
dict = {'Futebol': 5200, 'Tenis': 120, 'Natação': 698,'Volleyball': 1550}

#Criando uma série a partir de um dicionario
Obj3 = pd.Series(dict)

Obj3

#Criando uma lista
esportes = ['Futebol', 'Tenis', 'Natação', 'Basketball']

Obj4 = pd.Series(dict, index=esportes)

Obj4

pd.isnull(Obj4)# Retorna True or False em relação de conteudo nulo na série

pd.notnull(Obj4) #Retorna True or False em relação de conteudo não nulo na série

Obj4.isnull()

#Concatenandp series
Obj3 + Obj4

Obj4.name = 'população'

Obj4.index.name = 'esporte'