# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Introdução ao pandas
#DATAFRAMES
import pandas as pd
import numpy as np

data = { 'Estado':['Pernambuco','Santa Catarina', 'Paraná','Goiás','Bahia', 'Minas Gerais'],
        'Ano': [2019,2002,2003,2004,2005,2006],
        'População': [1.4,1.5,1.7,3.6,2.4,2.9]}

frame = pd.DataFrame(data)

frame

pd.DataFrame(data, columns=['Ano','Estado','População']) # Indica a ordem de exibição no dataframe

# Criando outro dataframe com os mesmos dados anteriores mas adicionando uma coluna
frame2 = pd.DataFrame(data, columns= ['Ano','Estado','População','Débito'],
                      index = ['um','dois','tres','quatro','cinco','seis'])

#Imprimindo o Dataframe
frame2

#Usando o Numpy para alimentar uma das colunas do dataframe
frame2['Débito'] = np.arange(6.)

frame2

frame2.values

#Resumo do Dataframe
frame2.describe()

frame2[ 'dois':'quatro']

frame2.loc['quatro']

frame2.iloc[2]

# Invertendo as Colunas e Índices
#Criando um dicionario
web_stats = {'Dias': [1,2,3,4,5,6,7],
             'Visitantes': [45,23,67,78,23,12,14],
             'Taxas': [11,22,33,44,55,66,77]}

df = pd.DataFrame(web_stats)

print(df)

#Visualizando uma coluna index
print(df.set_index('Dias'))

#Visualizando os 5 primeiros registros
print(df.head())

#Visualizando apenas uma coluna
print(df['Visitantes'])

#Personalizando a quantidade de colunas para visualização
print(df[['Visitantes','Taxas']])